#!/usr/bin/env python3
"""
build_cv.py -- generate the whole CV surface from one YAML file.

    _data/cv_source.yml
            |
            +--> _pages/cv.md            (website CV page)
            +--> _publications/*.md      (/publications/ collection)
            +--> _talks/*.md             (/talks/ collection)
            +--> _teaching/*.md          (/teaching/ collection)
            +--> cv/cv.tex               (moderncv source -> files/cv.pdf)

Every file listed above is OVERWRITTEN on each run. Do not hand-edit them.
Files generated by a previous run that are no longer in the YAML are deleted;
the list of what we generated lives in .cv-generated.json.

Usage:
    python3 scripts/build_cv.py                 # build everything
    python3 scripts/build_cv.py --check         # fail if output would change
    python3 scripts/build_cv.py --only tex      # md | collections | tex
"""

import argparse
import io
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required:  pip3 install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "_data", "cv_source.yml")
MANIFEST = os.path.join(ROOT, ".cv-generated.json")

WARNING_MD = (
    "<!-- DO NOT EDIT. Generated from _data/cv_source.yml by scripts/build_cv.py. "
    "Run `make cv` after editing the YAML. -->"
)
WARNING_TEX = (
    "% DO NOT EDIT. Generated from _data/cv_source.yml by scripts/build_cv.py.\n"
    "% Edit cv/preamble.tex to change styling.\n"
)

written = []


# ---------------------------------------------------------------- helpers ----
def write(path, content):
    """Write UTF-8 text, creating parent dirs, and record it in the manifest."""
    full = path if os.path.isabs(path) else os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with io.open(full, "w", encoding="utf-8") as fh:
        fh.write(content)
    written.append(os.path.relpath(full, ROOT))


# Characters pdflatex + inputenc can typeset: ASCII, Latin-1 Supplement and
# Latin Extended-A (accents), plus the punctuation we actually use. Anything
# else -- emoji, symbols, CJK -- is dropped from the PDF with a warning, but is
# kept on the website, where the browser handles it fine.
TEX_EXTRA_OK = "\u2010\u2011\u2012\u2013\u2014\u2018\u2019\u201c\u201d\u2026\u2032\u2033\u00b0\n\t"


def _tex_ok(ch):
    cp = ord(ch)
    return (0x20 <= cp <= 0x7E          # ASCII printable
            or 0xA0 <= cp <= 0x17F      # Latin-1 Supplement + Latin Extended-A
            or ch in TEX_EXTRA_OK)


_dropped_glyphs = set()


def tex_safe(s):
    """Drop glyphs pdflatex cannot render, remembering them for a warning."""
    kept = []
    for ch in s:
        if _tex_ok(ch):
            kept.append(ch)
        else:
            _dropped_glyphs.add(ch)
    return re.sub(r"[ ]+", " ", "".join(kept)).strip()


def tex_escape(s):
    """Escape LaTeX specials. Leaves accented UTF-8 characters alone."""
    if s is None:
        return ""
    s = tex_safe(str(s))
    for a, b in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ):
        s = s.replace(a, b)
    s = s.replace("–", "--").replace("—", "---")
    s = s.replace("“", "``").replace("”", "''")
    s = s.replace("‘", "`").replace("’", "'")
    # Straight double quotes -> LaTeX open/close pairs
    parts = s.split('"')
    if len(parts) > 1:
        out, opening = parts[0], True
        for p in parts[1:]:
            out += ("``" if opening else "''") + p
            opening = not opening
        s = out
    return s


def md_escape(s):
    """Markdown needs almost nothing escaped here; normalise whitespace only."""
    if s is None:
        return ""
    return re.sub(r"\s+", " ", str(s)).strip()


def emph_md(s):
    return "*%s*" % s


def emph_tex(s):
    return r"\textit{%s}" % s


def doi_url(doi):
    return "https://doi.org/%s" % doi


def pub_tail(p, fmt):
    """Shared trailing text of a publication reference: venue, details, DOI."""
    esc = tex_escape if fmt == "tex" else md_escape
    emph = emph_tex if fmt == "tex" else emph_md
    bits = []
    if p.get("venue"):
        bits.append(emph(esc(p["venue"])))
    if p.get("details"):
        bits.append(esc(p["details"]))
    tail = ", ".join(bits)
    if p.get("doi"):
        if fmt == "tex":
            tail += ". DOI: %s" % tex_escape(p["doi"])
        else:
            tail += ". [DOI: %s](%s)" % (md_escape(p["doi"]), doi_url(p["doi"]))
    return tail


def pub_reference(p, fmt):
    esc = tex_escape if fmt == "tex" else md_escape
    ref = "%s %s" % (esc(p["authors"]), esc(p["title"]))
    tail = pub_tail(p, fmt)
    return ref + (" " + tail if tail else "")


TODO_MARKERS = ("", "todo", "tbd", "none")


def talk_title(t):
    """The talk's own title, or None if it has none / is still a placeholder."""
    title = (t.get("title") or "").strip()
    return None if title.lower() in TODO_MARKERS else title


def talk_line(t, fmt):
    """
    'Title of the talk.' Meeting name. Location. Format.

    With no title yet, degrades to exactly the old form: Meeting. Location.
    Format. -- so partially-filled data always reads correctly.
    """
    esc = tex_escape if fmt == "tex" else md_escape
    bits = [esc(x) for x in (t.get("meeting") or t.get("title"),
                             t.get("location"), t.get("format")) if x]
    line = ". ".join(bits) + "."

    title = talk_title(t)
    if not title:
        return line
    clean = title.rstrip(".")
    quoted = ('"%s."' % md_escape(clean) if fmt == "md"
              else "``%s.''" % tex_escape(clean))
    return quoted + " " + line


def split_pubs(data):
    pubs = data.get("publications", [])
    first = [p for p in pubs if p.get("authorship", "first") == "first"]
    co = [p for p in pubs if p.get("authorship") == "co"]
    # In-progress first, then newest to oldest by date.
    key = lambda p: (0 if p.get("status") == "in_progress" else 1,
                     _desc(str(p.get("date", p.get("year", "")))))
    return sorted(first, key=key), sorted(co, key=key)


def split_talks(data):
    """Newest first, using the full date so within-year order is controllable."""
    talks = data.get("talks", [])
    key = lambda t: _desc(str(t.get("date", "")))
    invited = sorted([t for t in talks if t.get("group") == "invited"], key=key)
    contributed = sorted([t for t in talks if t.get("group") != "invited"], key=key)
    return invited, contributed


def _desc(s):
    """Sort key that orders strings in reverse (newest date first)."""
    return tuple(-ord(c) for c in s)


SMALL_WORDS = {"and", "or", "of", "for", "the", "a", "an", "in", "on", "to", "with"}


def titleize(key, title_case=False):
    """personal_interests -> 'Personal interests', or 'Personal Interests'."""
    words = key.replace("_", " ").split()
    if not title_case:
        return " ".join(words).capitalize()
    return " ".join(w.capitalize() if i == 0 or w not in SMALL_WORDS else w
                    for i, w in enumerate(words))


def title_for(data, key, table, title_case=False):
    """Heading: explicit `section_titles:` override, then built-in, then derived."""
    custom = (data.get("section_titles") or {}).get(key)
    return custom or table.get(key) or titleize(key, title_case)


def generic_items(value):
    """
    Normalise an unrecognised section into (hint, text) pairs, so ANY new key
    added to cv_source.yml renders without touching this file. Shapes accepted:

        key: a paragraph of prose                       -> one unhinted line
        key: [plain string, plain string]               -> unhinted bullets
        key: [{date|dates|label|term|year: .., text: ..}] -> hinted bullets
    """
    if value is None:
        return []
    if isinstance(value, str):
        return [("", value)]
    items = []
    for entry in value:
        if isinstance(entry, str):
            items.append(("", entry))
        elif isinstance(entry, dict):
            hint = next((entry[k] for k in ("date", "dates", "label", "term", "year")
                         if entry.get(k)), "")
            items.append((str(hint), str(entry.get("text") or entry.get("title") or "")))
    return items


# ------------------------------------------------------------ markdown CV ----
MD_SECTION_TITLES = {
    "research_interests": "Research interests",
    "education": "Education",
    "research_experience": "Research experience",
    "industry_experience": "Industry experience",
    "technical_expertise": "Technical expertise",
    "publications": "Publications",
    "patents": "Patents",
    "invited_talks": "Invited talks",
    "conference_presentations": "Conference presentations, workshops, and seminars",
    "teaching": "Teaching",
    "guest_lectures": "Guest lectures",
    "service": "Leadership, service, and mentorship",
    "honors": "Honors and awards",
    "activities": "Activities",
}


def md_entry(dates, title, org, location, extra=None, bullets=None):
    out = ["* %s: %s" % (md_escape(dates), md_escape(title))]
    where = ", ".join(x for x in [md_escape(org), md_escape(location)] if x)
    if where:
        out.append("  * %s" % where)
    if extra:
        out.append("  * %s" % md_escape(extra))
    for b in bullets or []:
        out.append("  * %s" % md_escape(b).rstrip("."))
    return "\n".join(out)


def build_markdown(data):
    b = data["basics"]
    L = [
        "---",
        "layout: archive",
        'title: "CV"',
        "permalink: /cv/",
        "author_profile: true",
        "redirect_from:",
        "  - /resume",
        "---",
        "",
        WARNING_MD,
        "",
        "{% include base_path %}",
        "",
        "[Download this CV as a PDF]({{ base_path }}/files/cv.pdf)",
        "",
    ]

    def head(key):
        L.extend([title_for(data, key, MD_SECTION_TITLES), "=" * 6])

    for key in data["section_order"]:
        if key not in MD_SECTION_TITLES:
            # Unknown key -> render generically. No code change needed to add one.
            head(key)
            for hint, text in generic_items(data.get(key)):
                L.append(("* %s: %s" % (md_escape(hint), md_escape(text)))
                         if hint else "* %s" % md_escape(text))
            L.append("")

        elif key == "research_interests":
            head(key)
            L.extend([md_escape(data["research_interests"]), ""])

        elif key == "education":
            head(key)
            for e in data["education"]:
                L.append("* %s, %s, %s" % (md_escape(e["degree"]), md_escape(e["institution"]), e["year"]))
                for n in e.get("notes", []):
                    L.append("  * %s" % md_escape(n))
            L.append("")

        elif key in ("research_experience", "industry_experience"):
            head(key)
            for j in data.get(key, []):
                L.append(md_entry(j["dates"], j["title"], j["org"], j["location"],
                                  j.get("advisor"), j.get("bullets")))
                L.append("")

        elif key == "technical_expertise":
            head(key)
            for t in data["technical_expertise"]:
                L.append("* %s: %s" % (md_escape(t["label"]), md_escape(t["text"]).rstrip(".")))
            L.append("")

        elif key == "publications":
            head(key)
            L.append("")
            first, co = split_pubs(data)
            for label, group in (("First-author publications", first),
                                 ("Co-author publications", co)):
                if not group:
                    continue
                L.extend([label, "-" * 6])
                for p in group:
                    year = "*In progress*" if p.get("status") == "in_progress" else str(p["year"])
                    L.append("* %s: %s" % (year, pub_reference(p, "md")))
                L.append("")

        elif key == "patents":
            head(key)
            for p in data.get("patents", []):
                line = "* %s: %s" % (p["year"], md_escape(p["text"]))
                if p.get("url"):
                    line += " [Link](%s)" % p["url"]
                L.append(line)
            L.append("")

        elif key in ("invited_talks", "conference_presentations"):
            head(key)
            invited, contributed = split_talks(data)
            for t in (invited if key == "invited_talks" else contributed):
                L.append("* %s: %s" % (t["year"], talk_line(t, "md")))
            L.append("")

        elif key == "teaching":
            head(key)
            for t in data.get("teaching", []):
                L.append(md_entry(t["dates"], t["title"], t["org"], t["location"],
                                  bullets=t.get("bullets")))
                L.append("")

        elif key == "guest_lectures":
            head(key)
            for g in data.get("guest_lectures", []):
                L.append("* %s: %s. *%s*. %s." % (
                    md_escape(g["term"]), md_escape(g["title"]),
                    md_escape(g["course"]), md_escape(g["org"])))
            L.append("")

        elif key == "service":
            head(key)
            s = data["service"]
            for r in s.get("roles", []):
                L.append("* %s: %s, %s" % (md_escape(r["dates"]), md_escape(r["title"]), md_escape(r["org"])))
                for bl in r.get("bullets", []):
                    L.append("  * %s" % md_escape(bl).rstrip("."))
            for it in s.get("items", []):
                L.append("* %s: %s" % (md_escape(it["label"]), md_escape(it["text"])))
            if s.get("mentorship"):
                L.append("* Mentorship:")
                for m in s["mentorship"]:
                    L.append("  * %s" % md_escape(m).rstrip("."))
            L.append("")

        elif key in ("honors", "activities"):
            head(key)
            for h in data.get(key, []):
                L.append("* %s: %s" % (md_escape(h["date"]), md_escape(h["text"])))
            L.append("")

    return "\n".join(L).rstrip() + "\n"


# ---------------------------------------------------------- collections ------
def yaml_str(s):
    """Quote a string safely for a YAML front-matter scalar."""
    return '"%s"' % md_escape(s).replace("\\", "\\\\").replace('"', '\\"')


def build_collections(data):
    # --- publications ---
    for p in data.get("publications", []):
        if p.get("site") is False or p.get("status") == "in_progress":
            continue
        citation = "%s (%s). &quot;%s&quot; <i>%s</i>%s." % (
            p["authors"], p["year"], p["title"], p["venue"],
            ", " + p["details"] if p.get("details") else "")
        body = ""
        if p.get("doi"):
            body = "\n[Read the paper](%s)\n" % doi_url(p["doi"])
        fm = [
            "---",
            "title: %s" % yaml_str(p["title"]),
            "collection: publications",
            "category: manuscripts",
            "permalink: /publication/%s-%s" % (p["date"], p["slug"]),
            "excerpt: %s" % yaml_str(p.get("excerpt", "")),
            "date: %s" % p["date"],
            "venue: %s" % yaml_str(p["venue"]),
        ]
        if p.get("doi"):
            fm.append("paperurl: %s" % yaml_str(doi_url(p["doi"])))
        fm += ["citation: %s" % yaml_str(citation), "---", "", WARNING_MD, body]
        write("_publications/%s-%s.md" % (p["date"], p["slug"]), "\n".join(fm))

    # --- talks ---
    for t in data.get("talks", []):
        if t.get("site") is False:
            continue
        # Page heading is the talk's own title once known; until then the
        # meeting name stands in, so the page is never headed "TODO".
        title = talk_title(t)
        meeting = t.get("meeting") or t.get("title")
        fm = [
            "---",
            "title: %s" % yaml_str(title or meeting),
            "collection: talks",
            "type: %s" % yaml_str(t.get("format") or t.get("type", "Talk")),
            "permalink: /talks/%s" % t["slug"],
            "venue: %s" % yaml_str(meeting or t.get("venue", "")),
            "date: %s" % t["date"],
            "location: %s" % yaml_str(t["location"]),
            "---",
            "",
            WARNING_MD,
            "",
        ]
        if title and meeting:
            fm.append("Presented at %s." % md_escape(meeting))
            fm.append("")
        write("_talks/%s.md" % t["slug"], "\n".join(fm))

    # --- teaching (courses + guest lectures both live here) ---
    for t in data.get("teaching", []):
        body = "\n".join("- %s" % md_escape(b) for b in t.get("bullets", []))
        fm = [
            "---",
            "title: %s" % yaml_str(t["title"]),
            "collection: teaching",
            "type: %s" % yaml_str(t.get("type", "Course")),
            "permalink: /teaching/%s" % t["slug"],
            "venue: %s" % yaml_str(t["org"]),
            "date: %s" % t["date"],
            "location: %s" % yaml_str(t["location"]),
            "---",
            "",
            WARNING_MD,
            "",
            md_escape(t["dates"]) + ".",
            "",
            body,
            "",
        ]
        write("_teaching/%s.md" % t["slug"], "\n".join(fm))

    for g in data.get("guest_lectures", []):
        fm = [
            "---",
            "title: %s" % yaml_str("Guest lecture: " + g["title"]),
            "collection: teaching",
            'type: "Guest lecture"',
            "permalink: /teaching/%s" % g["slug"],
            "venue: %s" % yaml_str("%s, %s" % (g["org"], g["course"])),
            "date: %s" % g["date"],
            "location: %s" % yaml_str(g["location"]),
            "---",
            "",
            WARNING_MD,
            "",
            "%s." % md_escape(g["term"]),
            "",
            "Guest lecture delivered in the course *%s*." % md_escape(g["course"]),
            "",
        ]
        write("_teaching/%s.md" % g["slug"], "\n".join(fm))


# ------------------------------------------------------------------ LaTeX ----
TEX_SECTION_TITLES = {
    "research_interests": "Research Interests",
    "education": "Education",
    "research_experience": "Research Experience",
    "industry_experience": "Industry Experience",
    "technical_expertise": "Technical Expertise",
    "publications": "Publications",
    "patents": "Patents",
    "invited_talks": "Invited Talks",
    "conference_presentations": "Conference Presentations, Workshops, and Seminars",
    "teaching": "Teaching Experience",
    "guest_lectures": "Guest Lectures",
    "service": "Leadership, Service, and Mentorship",
    "honors": "Honors and Awards",
    "activities": "Activities",
}

DEFAULT_PREAMBLE = r"""% Styling for the generated CV. Safe to edit by hand.
\documentclass[11pt,letterpaper,sans]{moderncv}

\moderncvstyle{classic}
\moderncvcolor{blue}

\usepackage[utf8]{inputenc}
\usepackage[scale=0.82]{geometry}
\setlength{\hintscolumnwidth}{3.2cm}
\setlength{\makecvtitlenamewidth}{10cm}

\usepackage{xurl}
\usepackage{enumitem}
\setlist[itemize]{leftmargin=*, itemsep=0.15em, topsep=0.15em}
"""


def tex_itemize(bullets):
    if not bullets:
        return "{}"
    lines = ["{%", r"\begin{itemize}"]
    for bl in bullets:
        lines.append(r"    \item %s" % tex_escape(md_escape(bl)))
    lines += [r"\end{itemize}}"]
    return "\n".join(lines)


def cventry(dates, title, org, location, extra, bullets):
    return r"\cventry{%s}{%s}{%s}{%s}{%s}%s" % (
        tex_escape(dates), tex_escape(title), tex_escape(org),
        tex_escape(location), tex_escape(extra or ""), tex_itemize(bullets))


def build_tex(data):
    b = data["basics"]
    preamble_path = os.path.join(ROOT, "cv", "preamble.tex")
    if os.path.exists(preamble_path):
        preamble = io.open(preamble_path, encoding="utf-8").read()
    else:
        # Seeded once, then owned by the user -- deliberately NOT recorded in the
        # manifest, so it is never overwritten or pruned by later builds.
        preamble = DEFAULT_PREAMBLE
        os.makedirs(os.path.dirname(preamble_path), exist_ok=True)
        with io.open(preamble_path, "w", encoding="utf-8") as fh:
            fh.write(DEFAULT_PREAMBLE)
        print("  seeded cv/preamble.tex (edit this to change PDF styling)")

    L = [WARNING_TEX, preamble, ""]
    L.append(r"\firstname{%s}" % tex_escape(b["first_name"]))
    L.append(r"\familyname{%s}" % tex_escape(b["family_name"]))
    L.append(r"\email{%s}" % b["email"])
    if b.get("phone"):
        L.append(r"\phone[mobile]{%s}" % tex_escape(b["phone"]))
    if b.get("homepage"):
        L.append(r"\homepage{%s}" % b["homepage"])
    if b.get("github"):
        L.append(r"\social[github]{%s}" % b["github"])
    if b.get("orcid"):
        L.append(r"\social[orcid]{%s}" % b["orcid"])
    L += ["", r"\begin{document}", "", r"\makecvtitle", r"\vspace{-1.0em}", ""]

    def head(key):
        L.append(r"\section{%s}" % title_for(data, key, TEX_SECTION_TITLES, True))

    for key in data["section_order"]:
        if key not in TEX_SECTION_TITLES:
            # Unknown key -> render generically. No code change needed to add one.
            head(key)
            for hint, text in generic_items(data.get(key)):
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(hint),
                                               tex_escape(md_escape(text))))

        elif key == "research_interests":
            head(key)
            L.append(r"\cvitem{}{%s}" % tex_escape(md_escape(data["research_interests"])))

        elif key == "education":
            head(key)
            for e in data["education"]:
                notes = " ".join(md_escape(n).rstrip(".") + "." for n in e.get("notes", []))
                L.append(r"\cventry{%s}{%s}{%s}{%s}{}{%s}" % (
                    tex_escape(e["date"]), tex_escape(e["degree"]),
                    tex_escape(e["institution"]), tex_escape(e["location"]),
                    tex_escape(notes)))

        elif key in ("research_experience", "industry_experience"):
            head(key)
            for j in data.get(key, []):
                L.append(cventry(j["dates"], j["title"], j["org"], j["location"],
                                 j.get("advisor"), j.get("bullets")))
                L.append("")

        elif key == "technical_expertise":
            head(key)
            for t in data["technical_expertise"]:
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(t["label"]),
                                               tex_escape(md_escape(t["text"]))))

        elif key == "publications":
            head(key)
            first, co = split_pubs(data)
            for label, group in (("First-Author Publications", first),
                                 ("Co-Author Publications", co)):
                if not group:
                    continue
                L.append(r"\subsection{%s}" % label)
                for p in group:
                    year = "In progress" if p.get("status") == "in_progress" else str(p["year"])
                    L.append(r"\cvitem{%s}{%s}" % (tex_escape(year), pub_reference(p, "tex")))

        elif key == "patents":
            head(key)
            for p in data.get("patents", []):
                txt = tex_escape(md_escape(p["text"]))
                if p.get("url"):
                    txt += r" \url{%s}." % p["url"]
                L.append(r"\cvitem{%s}{%s}" % (p["year"], txt))

        elif key in ("invited_talks", "conference_presentations"):
            head(key)
            invited, contributed = split_talks(data)
            for t in (invited if key == "invited_talks" else contributed):
                L.append(r"\cvitem{%s}{%s}" % (t["year"], talk_line(t, "tex")))

        elif key == "teaching":
            head(key)
            for t in data.get("teaching", []):
                L.append(cventry(t["dates"], t["title"], t["org"], t["location"],
                                 None, t.get("bullets")))
                L.append("")

        elif key == "guest_lectures":
            head(key)
            for g in data.get("guest_lectures", []):
                L.append(r"\cvitem{%s}{%s. \textit{%s}. %s.}" % (
                    tex_escape(g["term"]), tex_escape(g["title"]),
                    tex_escape(g["course"]), tex_escape(g["org"])))

        elif key == "service":
            head(key)
            s = data["service"]
            for r in s.get("roles", []):
                L.append(cventry(r["dates"], r["title"], r["org"], "", None, r.get("bullets")))
            for it in s.get("items", []):
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(it["label"]),
                                               tex_escape(md_escape(it["text"]))))
            for i, m in enumerate(s.get("mentorship", [])):
                L.append(r"\cvitem{%s}{%s}" % ("Mentorship" if i == 0 else "",
                                               tex_escape(md_escape(m))))

        elif key in ("honors", "activities"):
            head(key)
            for h in data.get(key, []):
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(h["date"]),
                                               tex_escape(md_escape(h["text"]))))

        L.append("")

    L.append(r"\end{document}")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------- main ----
def prune_stale():
    """Delete files a previous run generated that this run did not."""
    if not os.path.exists(MANIFEST):
        return
    try:
        old = set(json.load(io.open(MANIFEST, encoding="utf-8")).get("files", []))
    except (ValueError, KeyError):
        return
    for rel in sorted(old - set(written)):
        path = os.path.join(ROOT, rel)
        if os.path.exists(path):
            try:
                os.remove(path)
                print("  removed stale %s" % rel)
            except OSError as exc:
                print("  WARNING could not remove %s (%s)" % (rel, exc))


# Keys that are configuration or are consumed by another section, so their
# absence from section_order is expected rather than a mistake.
NOT_SECTIONS = {"basics", "section_order", "section_titles", "talks"}


def validate(data):
    """Catch the easy mistakes: a section written but never displayed, or listed
    but never written."""
    msgs = []
    order = list(data.get("section_order", []))

    for key in data:
        if key in NOT_SECTIONS or key in order:
            continue
        if key in ("invited_talks", "conference_presentations"):
            continue
        msgs.append(
            "'%s' exists in cv_source.yml but is NOT in section_order, so it will "
            "not appear anywhere. Add it to section_order to show it." % key)

    virtual = {"invited_talks", "conference_presentations"}
    for key in order:
        if key not in data and key not in virtual:
            msgs.append("section_order lists '%s', but there is no such key in "
                        "cv_source.yml. It will render empty." % key)

    todo = [t["slug"] for t in data.get("talks", [])
            if (t.get("title") or "").strip().lower() in ("todo", "tbd")]
    if todo:
        msgs.append(
            "%d of %d talks still have `title: TODO` and are rendering from the "
            "meeting name only. Fill them in (or delete the title line if the "
            "talk had no title): %s"
            % (len(todo), len(data.get("talks", [])), ", ".join(todo[:3])
               + (", ..." if len(todo) > 3 else "")))
    return msgs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", choices=["md", "collections", "tex"], action="append")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any output differs from what is on disk")
    args = ap.parse_args()
    targets = args.only or ["md", "collections", "tex"]

    with io.open(SOURCE, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    warnings = validate(data)

    if args.check:
        stale = []
        if "md" in targets:
            stale += _diff("_pages/cv.md", build_markdown(data))
        if "tex" in targets:
            stale += _diff("cv/cv.tex", build_tex(data))
        if stale:
            print("Out of date (run `make cv`):\n  " + "\n  ".join(stale))
            return 1
        print("CV outputs are up to date.")
        return 0

    if "md" in targets:
        write("_pages/cv.md", build_markdown(data))
    if "collections" in targets:
        build_collections(data)
    if "tex" in targets:
        write("cv/cv.tex", build_tex(data))

    if set(targets) == {"md", "collections", "tex"}:
        prune_stale()
        json.dump({"files": sorted(written)}, io.open(MANIFEST, "w", encoding="utf-8"), indent=1)

    print("Generated %d file(s) from _data/cv_source.yml" % len(written))
    for msg in warnings:
        print("  WARNING: %s" % msg)
    if _dropped_glyphs:
        print("  NOTE: character(s) %s cannot be typeset by pdflatex and were "
              "left out of the PDF. They still appear on the website."
              % " ".join(sorted(_dropped_glyphs)))
    return 0


def _diff(rel, content):
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return [rel + " (missing)"]
    return [] if io.open(path, encoding="utf-8").read() == content else [rel]


if __name__ == "__main__":
    sys.exit(main())
