#!/usr/bin/env python3
"""
build_cv.py -- generate the whole CV surface from one YAML file.

    _data/cv_source.yml
            |
            +--> _pages/cv.md            (website CV page)
            +--> _publications/*.md      (/publications/ collection)
            +--> _talks/*.md             (/talks/ collection)
            +--> _teaching/*.md          (/teaching/ collection)
            +--> cv/cv.tex               (moderncv source -> files/cv.pdf)

Every file listed above is OVERWRITTEN on each run. Do not hand-edit them.
Files generated by a previous run that are no longer in the YAML are deleted;
the list of what we generated lives in .cv-generated.json.

Usage:
    python3 scripts/build_cv.py                 # build everything
    python3 scripts/build_cv.py --check         # fail if output would change
    python3 scripts/build_cv.py --only tex      # md | collections | tex
"""

import argparse
import io
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required:  pip3 install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "_data", "cv_source.yml")
MANIFEST = os.path.join(ROOT, ".cv-generated.json")

WARNING_MD = (
    "<!-- DO NOT EDIT. Generated from _data/cv_source.yml by scripts/build_cv.py. "
    "Run `make cv` after editing the YAML. -->"
)
WARNING_TEX = (
    "% DO NOT EDIT. Generated from _data/cv_source.yml by scripts/build_cv.py.\n"
    "% Edit cv/preamble.tex to change styling.\n"
)

written = []


# ----------------------------------------------------------- date display ----
# Display dates as MM/YYYY. Seasons and terms carry no month, so they collapse
# to the bare year, per the rule "if month is not provided just use YYYY".
# Set `date_style: words` in cv_source.yml to keep the original wording.
MONTHS = {"jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05",
          "jun": "06", "jul": "07", "aug": "08", "sep": "09", "sept": "09",
          "oct": "10", "nov": "11", "dec": "12"}
SEASONS = ("Fall", "Autumn", "Winter", "Spring", "Summer")
MONTH_RE = r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\.?"
ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def format_date_hint(text):
    """'Oct. 2023' -> '10/2023';  'Mar.-Jun. 2020' -> '03/2020-06/2020';
       'Fall 2024-Spring 2025' -> '2024-2025';  '2011-2016' -> unchanged."""
    if text is None:
        return text
    out = str(text)
    if ISO_RE.match(out.strip()):        # Jekyll's own date field -- leave alone
        return out

    # "Mar.-Jun. 2020" -- two months sharing one trailing year.
    def pair(m):
        a, b, year = MONTHS[m.group(1).lower()], MONTHS[m.group(2).lower()], m.group(3)
        return "%s/%s\u2013%s/%s" % (a, year, b, year)
    out = re.sub(MONTH_RE + r"\s*[\u2013\u2014-]\s*" + MONTH_RE + r"\s+(\d{4})",
                 pair, out)

    # "Oct. 2023" -> "10/2023"
    out = re.sub(MONTH_RE + r"\s+(\d{4})",
                 lambda m: "%s/%s" % (MONTHS[m.group(1).lower()], m.group(2)), out)

    # Seasons and terms have no month: drop the word, keep the year.
    for word in SEASONS:
        out = re.sub(r"\b%s\s+(?=\d{4})" % word, "", out)
    return re.sub(r"\s+", " ", out).strip()


def normalise_dates(node, enabled=True):
    """Rewrite every display-date field in the loaded YAML, in place."""
    if not enabled:
        return node
    if isinstance(node, dict):
        for k, v in node.items():
            if k in ("dates", "term", "date") and isinstance(v, str):
                node[k] = format_date_hint(v)
            else:
                normalise_dates(v)
    elif isinstance(node, list):
        for item in node:
            normalise_dates(item)
    return node


# ---------------------------------------------------------------- helpers ----
def write(path, content):
    """Write UTF-8 text, creating parent dirs, and record it in the manifest."""
    full = path if os.path.isabs(path) else os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with io.open(full, "w", encoding="utf-8") as fh:
        fh.write(content)
    written.append(os.path.relpath(full, ROOT))


# Characters pdflatex + inputenc can typeset: ASCII, Latin-1 Supplement and
# Latin Extended-A (accents), plus the punctuation we actually use. Anything
# else -- emoji, symbols, CJK -- is dropped from the PDF with a warning, but is
# kept on the website, where the browser handles it fine.
TEX_EXTRA_OK = "\u2010\u2011\u2012\u2013\u2014\u2018\u2019\u201c\u201d\u2026\u2032\u2033\u00b0\n\t"


def _tex_ok(ch):
    cp = ord(ch)
    return (0x20 <= cp <= 0x7E          # ASCII printable
            or 0xA0 <= cp <= 0x17F      # Latin-1 Supplement + Latin Extended-A
            or ch in TEX_EXTRA_OK)


_dropped_glyphs = set()


def tex_safe(s):
    """Drop glyphs pdflatex cannot render, remembering them for a warning."""
    kept = []
    for ch in s:
        if _tex_ok(ch):
            kept.append(ch)
        else:
            _dropped_glyphs.add(ch)
    return re.sub(r"[ ]+", " ", "".join(kept)).strip()


def tex_escape(s):
    """Escape LaTeX specials. Leaves accented UTF-8 characters alone."""
    if s is None:
        return ""
    s = tex_safe(str(s))
    for a, b in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
        ("|", r"\textbar{}"),   # a bare | renders as an em dash in TeX
    ):
        s = s.replace(a, b)
    s = s.replace("–", "--").replace("—", "---")
    s = s.replace("“", "``").replace("”", "''")
    s = s.replace("‘", "`").replace("’", "'")
    # Straight double quotes -> LaTeX open/close pairs
    parts = s.split('"')
    if len(parts) > 1:
        out, opening = parts[0], True
        for p in parts[1:]:
            out += ("``" if opening else "''") + p
            opening = not opening
        s = out
    return s


# This site runs kramdown with `input: GFM`, whose table detection fires on ANY
# line containing a pipe -- no header row needed. A literal "|" anywhere in the
# CV therefore renders as a stray one-cell table. Emitting the numeric entity
# instead sidesteps table detection entirely (which scans raw text) while still
# displaying a real pipe, because `entity_output: as_char` converts it back.
MD_PIPE = "&#124;"


def norm_ws(s):
    """Collapse whitespace. Format-neutral -- safe before either escaper."""
    if s is None:
        return ""
    return re.sub(r"\s+", " ", str(s)).strip()


def md_escape(s):
    """Whitespace + neutralise pipes so kramdown sees no tables. MARKDOWN ONLY.

    Never feed the result to tex_escape: the entity's '#' would be escaped and
    the PDF would print a literal "&#124;".
    """
    return norm_ws(s).replace("|", MD_PIPE)


def emph_md(s):
    return "*%s*" % s


def emph_tex(s):
    return r"\textit{%s}" % s


def doi_url(doi):
    return "https://doi.org/%s" % doi


def pub_tail(p, fmt):
    """Shared trailing text of a publication reference: venue, details, DOI."""
    esc = tex_escape if fmt == "tex" else md_escape
    emph = emph_tex if fmt == "tex" else emph_md
    bits = []
    if p.get("venue"):
        bits.append(emph(esc(p["venue"])))
    if p.get("details"):
        bits.append(esc(p["details"]))
    tail = ", ".join(bits)
    if p.get("doi"):
        if fmt == "tex":
            tail += ". DOI: %s" % tex_escape(p["doi"])
        else:
            tail += ". [DOI: %s](%s)" % (md_escape(p["doi"]), doi_url(p["doi"]))
    return tail


DEFAULT_BOLD_NAMES = ["Hoffman, L.", "L. Hoffman"]


def bold_names(data):
    """Names to embolden in author lists; override with `basics.bold_name:`."""
    configured = (data.get("basics") or {}).get("bold_name")
    if not configured:
        return DEFAULT_BOLD_NAMES
    return configured if isinstance(configured, list) else [configured]


def bold_own_name(authors, fmt, names):
    """Wrap the CV owner's name in bold wherever it appears in an author list."""
    # Longest first, so "Hoffman, L." wins over a bare "Hoffman".
    for name in sorted(names, key=len, reverse=True):
        marked = ("**%s**" % name) if fmt == "md" else (r"\textbf{%s}" % name)
        if name in authors and marked not in authors:
            authors = authors.replace(name, marked)
            break
    return authors


def pub_reference(p, fmt, names=None):
    esc = tex_escape if fmt == "tex" else md_escape
    # Escape first, then bold, so the bold markup itself is never escaped.
    authors = bold_own_name(esc(p["authors"]), fmt, names or DEFAULT_BOLD_NAMES)
    ref = "%s %s" % (authors, esc(p["title"]))
    tail = pub_tail(p, fmt)
    return ref + (" " + tail if tail else "")


TODO_MARKERS = ("", "todo", "tbd", "none")


def talk_title(t):
    """The talk's own title, or None if it has none / is still a placeholder."""
    title = (t.get("title") or "").strip()
    return None if title.lower() in TODO_MARKERS else title


def talk_line(t, fmt):
    """
    'Title of the talk.' Meeting name. Location. Format.

    With no title yet, degrades to exactly the old form: Meeting. Location.
    Format. -- so partially-filled data always reads correctly.
    """
    esc = tex_escape if fmt == "tex" else md_escape
    bits = [esc(x) for x in (t.get("meeting") or t.get("title"),
                             t.get("location"), t.get("format")) if x]
    line = ". ".join(bits) + "."

    title = talk_title(t)
    if not title:
        return line
    clean = title.rstrip(".")
    quoted = ('"%s."' % md_escape(clean) if fmt == "md"
              else "``%s.''" % tex_escape(clean))
    return quoted + " " + line


def split_pubs(data):
    pubs = data.get("publications", [])
    first = [p for p in pubs if p.get("authorship", "first") == "first"]
    co = [p for p in pubs if p.get("authorship") == "co"]
    # In-progress first, then newest to oldest by date.
    key = lambda p: (0 if p.get("status") == "in_progress" else 1,
                     _desc(str(p.get("date", p.get("year", "")))))
    return sorted(first, key=key), sorted(co, key=key)


DEFAULT_TALK_SECTIONS = {"invited_talks": "invited",
                         "conference_presentations": "contributed"}


def talk_sections(data):
    return data.get("talk_sections") or DEFAULT_TALK_SECTIONS


def talks_for_section(data, section_key):
    """Talks whose `group:` maps to this section, newest first."""
    group = talk_sections(data).get(section_key)
    if group is None:
        return []
    known = set(talk_sections(data).values())
    picked = [t for t in data.get("talks", [])
              # An unrecognised group falls into the last section rather than
              # vanishing silently.
              if t.get("group") == group
              or (t.get("group") not in known
                  and group == list(talk_sections(data).values())[-1])]
    return sorted(picked, key=lambda t: _desc(str(t.get("date", ""))))


def _desc(s):
    """Sort key that orders strings in reverse (newest date first)."""
    return tuple(-ord(c) for c in s)


SMALL_WORDS = {"and", "or", "of", "for", "the", "a", "an", "in", "on", "to", "with"}


def titleize(key, title_case=False):
    """personal_interests -> 'Personal interests', or 'Personal Interests'."""
    words = key.replace("_", " ").split()
    if not title_case:
        return " ".join(words).capitalize()
    return " ".join(w.capitalize() if i == 0 or w not in SMALL_WORDS else w
                    for i, w in enumerate(words))


def title_for(data, key, table, title_case=False):
    """Heading: explicit `section_titles:` override, then built-in, then derived."""
    custom = (data.get("section_titles") or {}).get(key)
    return custom or table.get(key) or titleize(key, title_case)


def generic_items(value, fmt="md", sep=None, bold=True):
    """
    Normalise an unrecognised section into (hint, text) pairs, so ANY new key
    added to cv_source.yml renders without touching this file. Shapes accepted:

        key: a paragraph of prose                        -> one unhinted line
        key: [plain string, plain string]                -> unhinted bullets
        key: [{date|dates|label|term: .., text: ..}]      -> hinted bullets
        key: {compact: true, entries: [...]}             -> compact one-liners
    """
    sep = DEFAULT_SEPARATOR if sep is None else sep
    if value is None:
        return []
    if isinstance(value, str):
        return [("", md_escape(value) if fmt == "md" else tex_escape(value))]
    items = []
    for entry in compact_entries(value):        # unwraps {compact:, entries:}
        if isinstance(entry, str):
            items.append(("", md_escape(entry) if fmt == "md" else tex_escape(entry)))
        elif isinstance(entry, dict):
            items.append(compact_line(entry, fmt, sep, bold))
    return items


DEFAULT_SEPARATOR = "; "


def bold_roles(data):
    """Bold the position title in compact entries. `bold_roles: false` to stop."""
    return data.get("bold_roles", True)


def separator(data):
    """Separator between parts of a compact entry. `compact_separator:` in YAML."""
    return data.get("compact_separator", DEFAULT_SEPARATOR)


def compact_line(e, fmt="md", sep=DEFAULT_SEPARATOR, bold=True):
    """
    One-line entry, Gregory-style:  Who, Role | Org  -- or Label: text.
    Assembled from whichever of these keys are present.
    """
    esc = md_escape if fmt == "md" else tex_escape
    hint = e.get("dates") or e.get("date") or ""

    if e.get("label") and e.get("text"):
        return e["label"], esc(e["text"])

    # The position title is emphasised; everything else is plain. Bolding is
    # applied AFTER escaping, so the markup itself is never escaped.
    role = esc(e["role"]) if e.get("role") else ""
    if role and bold:
        role = ("**%s**" % role) if fmt == "md" else (r"\textbf{%s}" % role)
    left = ", ".join(x for x in (esc(e["who"]) if e.get("who") else "", role) if x)
    right = sep.join(esc(x) for x in (e.get("org"), e.get("note"), e.get("text")) if x)
    return hint, sep.join(x for x in (left, right) if x)


def compact_entries(value):
    """A section written as {compact: true, entries: [...]} -> list of entries."""
    if isinstance(value, dict):
        return value.get("entries", [])
    return value or []


def is_compact(value):
    return isinstance(value, dict) and value.get("compact", True)


def merged_sections(data):
    """{display_key: [source_key, ...]} -- render several data blocks as one."""
    return data.get("merged_sections") or {}


def merged_members(data):
    out = set()
    for sources in merged_sections(data).values():
        out.update(sources)
    return out


def as_compact(source_key, e):
    """Map a source section's entry shape onto the compact {role, text} shape,
    so different kinds of entry can share one merged section."""
    if source_key == "teaching":
        # `role` is the bolded position; `title` is kept for the /teaching/ page.
        return {"dates": e.get("dates"),
                "role": e.get("role") or e.get("title"),
                "text": e.get("summary") or e.get("org")}
    if source_key == "guest_lectures":
        return {"dates": e.get("term"),
                "role": e.get("role") or "Guest Lecturer",
                "text": "; ".join(x for x in (e.get("title"), e.get("course"),
                                              e.get("org")) if x)}
    return e          # already a compact entry


def merged_entries(data, key):
    """Every entry of a merged section, in source order."""
    items = []
    for src in merged_sections(data).get(key, []):
        for e in compact_entries(data.get(src)):
            items.append(as_compact(src, e))
    return items


# ------------------------------------------------------------ markdown CV ----
MD_SECTION_TITLES = {
    "research_interests": "Research interests",
    "education": "Education",
    "research_experience": "Research experience",
    "industry_experience": "Industry experience",
    "technical_expertise": "Technical expertise",
    "publications": "Publications",
    "patents": "Patents",
    "invited_talks": "Invited talks",
    "conference_presentations": "Conference presentations, workshops, and seminars",
    "teaching": "Teaching",
    "guest_lectures": "Guest lectures",
    "mentorship": "Mentorship",
    "leadership": "Leadership",
    "service": "Service",
    "honors": "Honors and awards",
    "activities": "Activities",
}


def md_entry(dates, title, org, location, extra=None, bullets=None):
    out = ["* %s: %s" % (md_escape(dates), md_escape(title))]
    where = ", ".join(x for x in [md_escape(org), md_escape(location)] if x)
    if where:
        out.append("  * %s" % where)
    if extra:
        out.append("  * %s" % md_escape(extra))
    for b in bullets or []:
        out.append("  * %s" % md_escape(b).rstrip("."))
    return "\n".join(out)


def build_markdown(data):
    b = data["basics"]
    L = [
        "---",
        "layout: archive",
        'title: "CV"',
        "permalink: /cv/",
        "author_profile: true",
        "redirect_from:",
        "  - /resume",
        "---",
        "",
        WARNING_MD,
        "",
        "{% include base_path %}",
        "",
        "[Download this CV as a PDF]({{ base_path }}/files/cv.pdf)",
        "",
    ]

    def head(key):
        L.extend([title_for(data, key, MD_SECTION_TITLES), "=" * 6])

    for key in data["section_order"]:
        if key in merged_sections(data):
            head(key)
            for e in merged_entries(data, key):
                hint, body = compact_line(e, "md", separator(data), bold_roles(data))
                L.append("* %s: %s" % (md_escape(hint), body) if hint
                         else "* %s" % body)
            L.append("")

        elif key not in MD_SECTION_TITLES and key not in talk_sections(data):
            # Unknown key -> render generically. No code change needed to add one.
            head(key)
            for hint, text in generic_items(data.get(key), "md", separator(data), bold_roles(data)):
                L.append(("* %s: %s" % (md_escape(hint), text))
                         if hint else "* %s" % text)
            L.append("")

        elif key == "research_interests":
            head(key)
            L.extend([md_escape(data["research_interests"]), ""])

        elif key == "education":
            head(key)
            for e in data["education"]:
                L.append("* %s, %s, %s" % (md_escape(e["degree"]), md_escape(e["institution"]), e["year"]))
                for n in e.get("notes", []):
                    L.append("  * %s" % md_escape(n))
            L.append("")

        elif key in ("research_experience", "industry_experience"):
            head(key)
            for j in data.get(key, []):
                L.append(md_entry(j["dates"], j["title"], j["org"], j["location"],
                                  j.get("advisor"), j.get("bullets")))
                L.append("")

        elif key == "technical_expertise":
            head(key)
            for t in data["technical_expertise"]:
                L.append("* %s: %s" % (md_escape(t["label"]), md_escape(t["text"]).rstrip(".")))
            L.append("")

        elif key == "publications":
            head(key)
            L.append("")
            first, co = split_pubs(data)
            for label, group in (("First-author publications", first),
                                 ("Co-author publications", co)):
                if not group:
                    continue
                L.extend([label, "-" * 6])
                for p in group:
                    year = "*In progress*" if p.get("status") == "in_progress" else str(p["year"])
                    L.append("* %s: %s" % (year, pub_reference(p, "md", bold_names(data))))
                L.append("")

        elif key == "patents":
            head(key)
            for p in data.get("patents", []):
                line = "* %s: %s" % (p["year"], md_escape(p["text"]))
                if p.get("url"):
                    line += " [Link](%s)" % p["url"]
                L.append(line)
            L.append("")

        elif key in talk_sections(data):
            head(key)
            for t in talks_for_section(data, key):
                L.append("* %s: %s" % (t["year"], talk_line(t, "md")))
            L.append("")

        elif key == "teaching":
            head(key)
            for t in compact_entries(data.get("teaching")):
                if is_compact(data.get("teaching")):
                    L.append("* %s: %s%s%s" % (
                        md_escape(t["dates"]), md_escape(t["title"]),
                        separator(data), md_escape(t.get("summary") or t["org"])))
                else:
                    L.append(md_entry(t["dates"], t["title"], t["org"],
                                      t["location"], bullets=t.get("bullets")))
                    L.append("")
            L.append("")

        elif key == "guest_lectures":
            head(key)
            for g in data.get("guest_lectures", []):
                L.append("* %s: %s. *%s*. %s." % (
                    md_escape(g["term"]), md_escape(g["title"]),
                    md_escape(g["course"]), md_escape(g["org"])))
            L.append("")

        elif key in ("mentorship", "leadership", "service"):
            head(key)
            for e in compact_entries(data.get(key)):
                hint, body = compact_line(e, "md", separator(data), bold_roles(data))
                L.append("* %s: %s" % (md_escape(hint), body) if hint
                         else "* %s" % body)
            L.append("")

        elif key in ("honors", "activities"):
            head(key)
            for h in data.get(key, []):
                L.append("* %s: %s" % (md_escape(h["date"]), md_escape(h["text"])))
            L.append("")

    return "\n".join(L).rstrip() + "\n"


# ---------------------------------------------------------- collections ------
def yaml_str(s):
    """Quote a string safely for a YAML front-matter scalar."""
    return '"%s"' % md_escape(s).replace("\\", "\\\\").replace('"', '\\"')


def build_collections(data):
    # --- publications ---
    for p in data.get("publications", []):
        if p.get("site") is False or p.get("status") == "in_progress":
            continue
        citation = "%s (%s). &quot;%s&quot; <i>%s</i>%s." % (
            p["authors"], p["year"], p["title"], p["venue"],
            ", " + p["details"] if p.get("details") else "")
        body = ""
        if p.get("doi"):
            body = "\n[Read the paper](%s)\n" % doi_url(p["doi"])
        fm = [
            "---",
            "title: %s" % yaml_str(p["title"]),
            "collection: publications",
            "category: manuscripts",
            "permalink: /publication/%s-%s" % (p["date"], p["slug"]),
            "excerpt: %s" % yaml_str(p.get("excerpt", "")),
            "date: %s" % p["date"],
            "venue: %s" % yaml_str(p["venue"]),
        ]
        if p.get("doi"):
            fm.append("paperurl: %s" % yaml_str(doi_url(p["doi"])))
        fm += ["citation: %s" % yaml_str(citation), "---", "", WARNING_MD, body]
        write("_publications/%s-%s.md" % (p["date"], p["slug"]), "\n".join(fm))

    # --- talks ---
    for t in data.get("talks", []):
        if t.get("site") is False:
            continue
        # Page heading is the talk's own title once known; until then the
        # meeting name stands in, so the page is never headed "TODO".
        title = talk_title(t)
        meeting = t.get("meeting") or t.get("title")
        fm = [
            "---",
            "title: %s" % yaml_str(title or meeting),
            "collection: talks",
            "type: %s" % yaml_str(t.get("format") or t.get("type", "Talk")),
            "permalink: /talks/%s" % t["slug"],
            "venue: %s" % yaml_str(meeting or t.get("venue", "")),
            "date: %s" % t["date"],
            "location: %s" % yaml_str(t["location"]),
            "---",
            "",
            WARNING_MD,
            "",
        ]
        if title and meeting:
            fm.append("Presented at %s." % md_escape(meeting))
            fm.append("")
        write("_talks/%s.md" % t["slug"], "\n".join(fm))

    # --- teaching (courses + guest lectures both live here) ---
    for t in compact_entries(data.get("teaching")):
        body = "\n".join("- %s" % md_escape(b) for b in t.get("bullets", []))
        fm = [
            "---",
            "title: %s" % yaml_str(t["title"]),
            "collection: teaching",
            "type: %s" % yaml_str(t.get("type", "Course")),
            "permalink: /teaching/%s" % t["slug"],
            "venue: %s" % yaml_str(t["org"]),
            "date: %s" % t["date"],
            "location: %s" % yaml_str(t["location"]),
            "---",
            "",
            WARNING_MD,
            "",
            md_escape(t["dates"]) + ".",
            "",
            body,
            "",
        ]
        write("_teaching/%s.md" % t["slug"], "\n".join(fm))

    for g in data.get("guest_lectures", []):
        fm = [
            "---",
            "title: %s" % yaml_str("Guest lecture: " + g["title"]),
            "collection: teaching",
            'type: "Guest lecture"',
            "permalink: /teaching/%s" % g["slug"],
            "venue: %s" % yaml_str("%s, %s" % (g["org"], g["course"])),
            "date: %s" % g["date"],
            "location: %s" % yaml_str(g["location"]),
            "---",
            "",
            WARNING_MD,
            "",
            "%s." % md_escape(g["term"]),
            "",
            "Guest lecture delivered in the course *%s*." % md_escape(g["course"]),
            "",
        ]
        write("_teaching/%s.md" % g["slug"], "\n".join(fm))


# ------------------------------------------------------------------ LaTeX ----
TEX_SECTION_TITLES = {
    "research_interests": "Research Interests",
    "education": "Education",
    "research_experience": "Research Experience",
    "industry_experience": "Industry Experience",
    "technical_expertise": "Technical Expertise",
    "publications": "Publications",
    "patents": "Patents",
    "invited_talks": "Invited Talks",
    "conference_presentations": "Conference Presentations, Workshops, and Seminars",
    "teaching": "Teaching Experience",
    "guest_lectures": "Guest Lectures",
    "mentorship": "Mentorship",
    "leadership": "Leadership",
    "service": "Service",
    "honors": "Honors and Awards",
    "activities": "Activities",
}

DEFAULT_PREAMBLE = r"""% Styling for the generated CV. Safe to edit by hand.
\documentclass[11pt,letterpaper,sans]{moderncv}

\moderncvstyle{classic}
\moderncvcolor{blue}

\usepackage[utf8]{inputenc}
\usepackage[scale=0.82]{geometry}
\setlength{\hintscolumnwidth}{3.2cm}
\setlength{\makecvtitlenamewidth}{10cm}

\usepackage{xurl}
\usepackage{enumitem}
\setlist[itemize]{leftmargin=*, itemsep=0.15em, topsep=0.15em}
"""


def tex_itemize(bullets):
    if not bullets:
        return "{}"
    lines = ["{%", r"\begin{itemize}"]
    for bl in bullets:
        lines.append(r"    \item %s" % tex_escape(norm_ws(bl)))
    lines += [r"\end{itemize}}"]
    return "\n".join(lines)


def cventry(dates, title, org, location, extra, bullets):
    return r"\cventry{%s}{%s}{%s}{%s}{%s}%s" % (
        tex_escape(dates), tex_escape(title), tex_escape(org),
        tex_escape(location), tex_escape(extra or ""), tex_itemize(bullets))


def build_tex(data):
    b = data["basics"]
    preamble_path = os.path.join(ROOT, "cv", "preamble.tex")
    if os.path.exists(preamble_path):
        preamble = io.open(preamble_path, encoding="utf-8").read()
    else:
        # Seeded once, then owned by the user -- deliberately NOT recorded in the
        # manifest, so it is never overwritten or pruned by later builds.
        preamble = DEFAULT_PREAMBLE
        os.makedirs(os.path.dirname(preamble_path), exist_ok=True)
        with io.open(preamble_path, "w", encoding="utf-8") as fh:
            fh.write(DEFAULT_PREAMBLE)
        print("  seeded cv/preamble.tex (edit this to change PDF styling)")

    L = [WARNING_TEX, preamble, ""]
    L.append(r"\firstname{%s}" % tex_escape(b["first_name"]))
    L.append(r"\familyname{%s}" % tex_escape(b["family_name"]))
    L.append(r"\email{%s}" % b["email"])
    if b.get("phone"):
        L.append(r"\phone[mobile]{%s}" % tex_escape(b["phone"]))
    if b.get("homepage"):
        L.append(r"\homepage{%s}" % b["homepage"])
    if b.get("github"):
        L.append(r"\social[github]{%s}" % b["github"])
    if b.get("orcid"):
        L.append(r"\social[orcid]{%s}" % b["orcid"])
    L += ["", r"\begin{document}", "", r"\makecvtitle", r"\vspace{-1.0em}", ""]

    def head(key):
        L.append(r"\section{%s}" % title_for(data, key, TEX_SECTION_TITLES, True))

    for key in data["section_order"]:
        if key in merged_sections(data):
            head(key)
            for e in merged_entries(data, key):
                hint, body = compact_line(e, "tex", separator(data), bold_roles(data))
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(hint), body))

        elif key not in TEX_SECTION_TITLES and key not in talk_sections(data):
            # Unknown key -> render generically. No code change needed to add one.
            head(key)
            for hint, text in generic_items(data.get(key), "tex",
                                            separator(data), bold_roles(data)):
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(hint), text))

        elif key == "research_interests":
            head(key)
            L.append(r"\cvitem{}{%s}" % tex_escape(norm_ws(data["research_interests"])))

        elif key == "education":
            head(key)
            for e in data["education"]:
                notes = " ".join(md_escape(n).rstrip(".") + "." for n in e.get("notes", []))
                L.append(r"\cventry{%s}{%s}{%s}{%s}{}{%s}" % (
                    tex_escape(e["date"]), tex_escape(e["degree"]),
                    tex_escape(e["institution"]), tex_escape(e["location"]),
                    tex_escape(notes)))

        elif key in ("research_experience", "industry_experience"):
            head(key)
            for j in data.get(key, []):
                L.append(cventry(j["dates"], j["title"], j["org"], j["location"],
                                 j.get("advisor"), j.get("bullets")))
                L.append("")

        elif key == "technical_expertise":
            head(key)
            for t in data["technical_expertise"]:
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(t["label"]),
                                               tex_escape(norm_ws(t["text"]))))

        elif key == "publications":
            head(key)
            first, co = split_pubs(data)
            for label, group in (("First-Author Publications", first),
                                 ("Co-Author Publications", co)):
                if not group:
                    continue
                L.append(r"\subsection{%s}" % label)
                for p in group:
                    year = "In progress" if p.get("status") == "in_progress" else str(p["year"])
                    L.append(r"\cvitem{%s}{%s}" % (tex_escape(year), pub_reference(p, "tex", bold_names(data))))

        elif key == "patents":
            head(key)
            for p in data.get("patents", []):
                txt = tex_escape(norm_ws(p["text"]))
                if p.get("url"):
                    txt += r" \url{%s}." % p["url"]
                L.append(r"\cvitem{%s}{%s}" % (p["year"], txt))

        elif key in talk_sections(data):
            head(key)
            for t in talks_for_section(data, key):
                L.append(r"\cvitem{%s}{%s}" % (t["year"], talk_line(t, "tex")))

        elif key == "teaching":
            head(key)
            for t in compact_entries(data.get("teaching")):
                if is_compact(data.get("teaching")):
                    # Join first, escape once, so the pipe becomes \textbar{}.
                    body = "%s%s%s" % (t["title"], separator(data),
                                       t.get("summary") or t["org"])
                    L.append(r"\cvitem{%s}{%s}" % (tex_escape(t["dates"]),
                                                   tex_escape(norm_ws(body))))
                else:
                    L.append(cventry(t["dates"], t["title"], t["org"],
                                     t["location"], None, t.get("bullets")))
                    L.append("")

        elif key == "guest_lectures":
            head(key)
            for g in data.get("guest_lectures", []):
                L.append(r"\cvitem{%s}{%s. \textit{%s}. %s.}" % (
                    tex_escape(g["term"]), tex_escape(g["title"]),
                    tex_escape(g["course"]), tex_escape(g["org"])))

        elif key in ("mentorship", "leadership", "service"):
            head(key)
            for e in compact_entries(data.get(key)):
                hint, body = compact_line(e, "tex", separator(data), bold_roles(data))
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(hint), body))

        elif key in ("honors", "activities"):
            head(key)
            for h in data.get(key, []):
                L.append(r"\cvitem{%s}{%s}" % (tex_escape(h["date"]),
                                               tex_escape(norm_ws(h["text"]))))

        L.append("")

    L.append(r"\end{document}")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------- main ----
def prune_stale():
    """Delete files a previous run generated that this run did not."""
    if not os.path.exists(MANIFEST):
        return
    try:
        old = set(json.load(io.open(MANIFEST, encoding="utf-8")).get("files", []))
    except (ValueError, KeyError):
        return
    for rel in sorted(old - set(written)):
        path = os.path.join(ROOT, rel)
        if os.path.exists(path):
            try:
                os.remove(path)
                print("  removed stale %s" % rel)
            except OSError as exc:
                print("  WARNING could not remove %s (%s)" % (rel, exc))


# Keys that are configuration or are consumed by another section, so their
# absence from section_order is expected rather than a mistake.
NOT_SECTIONS = {"basics", "section_order", "section_titles", "talks",
                "talk_sections", "merged_sections", "compact_separator",
                "date_style"}


def validate(data):
    """Catch the easy mistakes: a section written but never displayed, or listed
    but never written."""
    msgs = []
    order = list(data.get("section_order", []))

    members = merged_members(data)
    for key in data:
        if key in NOT_SECTIONS or key in order or key in members:
            continue
        if key in talk_sections(data):
            continue
        msgs.append(
            "'%s' exists in cv_source.yml but is NOT in section_order, so it will "
            "not appear anywhere. Add it to section_order to show it." % key)

    virtual = set(talk_sections(data)) | set(merged_sections(data))
    for key in order:
        if key not in data and key not in virtual:
            msgs.append("section_order lists '%s', but there is no such key in "
                        "cv_source.yml. It will render empty." % key)

    todo = [t["slug"] for t in data.get("talks", [])
            if (t.get("title") or "").strip().lower() in ("todo", "tbd")]
    if todo:
        msgs.append(
            "%d of %d talks still have `title: TODO` and are rendering from the "
            "meeting name only. Fill them in (or delete the title line if the "
            "talk had no title): %s"
            % (len(todo), len(data.get("talks", [])), ", ".join(todo[:3])
               + (", ..." if len(todo) > 3 else "")))
    return msgs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", choices=["md", "collections", "tex"], action="append")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any output differs from what is on disk")
    args = ap.parse_args()
    targets = args.only or ["md", "collections", "tex"]

    with io.open(SOURCE, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    normalise_dates(data, data.get("date_style", "numeric") == "numeric")
    warnings = validate(data)

    if args.check:
        stale = []
        if "md" in targets:
            stale += _diff("_pages/cv.md", build_markdown(data))
        if "tex" in targets:
            stale += _diff("cv/cv.tex", build_tex(data))
        if stale:
            print("Out of date (run `make cv`):\n  " + "\n  ".join(stale))
            return 1
        print("CV outputs are up to date.")
        return 0

    if "md" in targets:
        page = build_markdown(data)
        # Regression guard: a raw pipe reaching the page would render as a
        # stray table under kramdown's GFM parser (see MD_PIPE above).
        if "|" in page:
            bad = [l for l in page.split("\n") if "|" in l][:2]
            warnings.append("a raw '|' reached _pages/cv.md and will render as a "
                            "table on the website: %s" % " / ".join(bad))
        write("_pages/cv.md", page)
    if "collections" in targets:
        build_collections(data)
    if "tex" in targets:
        write("cv/cv.tex", build_tex(data))

    if set(targets) == {"md", "collections", "tex"}:
        prune_stale()
        json.dump({"files": sorted(written)}, io.open(MANIFEST, "w", encoding="utf-8"), indent=1)

    print("Generated %d file(s) from _data/cv_source.yml" % len(written))
    for msg in warnings:
        print("  WARNING: %s" % msg)
    if _dropped_glyphs:
        print("  NOTE: character(s) %s cannot be typeset by pdflatex and were "
              "left out of the PDF. They still appear on the website."
              % " ".join(sorted(_dropped_glyphs)))
    return 0


def _diff(rel, content):
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return [rel + " (missing)"]
    return [] if io.open(path, encoding="utf-8").read() == content else [rel]


if __name__ == "__main__":
    sys.exit(main())
